/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as wellnessEscrowSol from "./WellnessEscrow.sol";
export type { wellnessEscrowSol };
export type { ProviderRegistry } from "./ProviderRegistry";
