/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace ProviderRegistry {
  export type ProviderStruct = {
    providerAddress: AddressLike;
    serviceName: string;
    price: BigNumberish;
    category: string;
    completedOrders: BigNumberish;
    disputes: BigNumberish;
    isActive: boolean;
  };

  export type ProviderStructOutput = [
    providerAddress: string,
    serviceName: string,
    price: bigint,
    category: string,
    completedOrders: bigint,
    disputes: bigint,
    isActive: boolean
  ] & {
    providerAddress: string;
    serviceName: string;
    price: bigint;
    category: string;
    completedOrders: bigint;
    disputes: bigint;
    isActive: boolean;
  };
}

export interface ProviderRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "authorizedReputationUpdaters"
      | "getAllProviders"
      | "getProvidersByCategory"
      | "owner"
      | "providerAddresses"
      | "providers"
      | "registerProvider"
      | "renounceOwnership"
      | "setAuthorizedUpdater"
      | "transferOwnership"
      | "updateProviderDetails"
      | "updateReputation"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OwnershipTransferred"
      | "ProviderRegistered"
      | "ProviderUpdated"
      | "ReputationUpdated"
      | "UpdaterAuthorized"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "authorizedReputationUpdaters",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllProviders",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getProvidersByCategory",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "providerAddresses",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "providers",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerProvider",
    values: [string, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setAuthorizedUpdater",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateProviderDetails",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "updateReputation",
    values: [AddressLike, boolean]
  ): string;

  decodeFunctionResult(
    functionFragment: "authorizedReputationUpdaters",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllProviders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProvidersByCategory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "providerAddresses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "providers", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerProvider",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAuthorizedUpdater",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateProviderDetails",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateReputation",
    data: BytesLike
  ): Result;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProviderRegisteredEvent {
  export type InputTuple = [
    providerAddress: AddressLike,
    serviceName: string,
    price: BigNumberish,
    category: string
  ];
  export type OutputTuple = [
    providerAddress: string,
    serviceName: string,
    price: bigint,
    category: string
  ];
  export interface OutputObject {
    providerAddress: string;
    serviceName: string;
    price: bigint;
    category: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProviderUpdatedEvent {
  export type InputTuple = [
    providerAddress: AddressLike,
    price: BigNumberish,
    isActive: boolean
  ];
  export type OutputTuple = [
    providerAddress: string,
    price: bigint,
    isActive: boolean
  ];
  export interface OutputObject {
    providerAddress: string;
    price: bigint;
    isActive: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReputationUpdatedEvent {
  export type InputTuple = [
    providerAddress: AddressLike,
    completedOrders: BigNumberish,
    disputes: BigNumberish
  ];
  export type OutputTuple = [
    providerAddress: string,
    completedOrders: bigint,
    disputes: bigint
  ];
  export interface OutputObject {
    providerAddress: string;
    completedOrders: bigint;
    disputes: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpdaterAuthorizedEvent {
  export type InputTuple = [updater: AddressLike, isAuthorized: boolean];
  export type OutputTuple = [updater: string, isAuthorized: boolean];
  export interface OutputObject {
    updater: string;
    isAuthorized: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ProviderRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): ProviderRegistry;
  waitForDeployment(): Promise<this>;

  interface: ProviderRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  authorizedReputationUpdaters: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  getAllProviders: TypedContractMethod<
    [],
    [ProviderRegistry.ProviderStructOutput[]],
    "view"
  >;

  getProvidersByCategory: TypedContractMethod<
    [category: string],
    [ProviderRegistry.ProviderStructOutput[]],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  providerAddresses: TypedContractMethod<
    [arg0: BigNumberish],
    [string],
    "view"
  >;

  providers: TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, bigint, string, bigint, bigint, boolean] & {
        providerAddress: string;
        serviceName: string;
        price: bigint;
        category: string;
        completedOrders: bigint;
        disputes: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;

  registerProvider: TypedContractMethod<
    [serviceName: string, price: BigNumberish, category: string],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setAuthorizedUpdater: TypedContractMethod<
    [updater: AddressLike, isAuthorized: boolean],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateProviderDetails: TypedContractMethod<
    [price: BigNumberish, isActive: boolean],
    [void],
    "nonpayable"
  >;

  updateReputation: TypedContractMethod<
    [providerAddress: AddressLike, success: boolean],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "authorizedReputationUpdaters"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "getAllProviders"
  ): TypedContractMethod<[], [ProviderRegistry.ProviderStructOutput[]], "view">;
  getFunction(
    nameOrSignature: "getProvidersByCategory"
  ): TypedContractMethod<
    [category: string],
    [ProviderRegistry.ProviderStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "providerAddresses"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "providers"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, bigint, string, bigint, bigint, boolean] & {
        providerAddress: string;
        serviceName: string;
        price: bigint;
        category: string;
        completedOrders: bigint;
        disputes: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "registerProvider"
  ): TypedContractMethod<
    [serviceName: string, price: BigNumberish, category: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setAuthorizedUpdater"
  ): TypedContractMethod<
    [updater: AddressLike, isAuthorized: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateProviderDetails"
  ): TypedContractMethod<
    [price: BigNumberish, isActive: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateReputation"
  ): TypedContractMethod<
    [providerAddress: AddressLike, success: boolean],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "ProviderRegistered"
  ): TypedContractEvent<
    ProviderRegisteredEvent.InputTuple,
    ProviderRegisteredEvent.OutputTuple,
    ProviderRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "ProviderUpdated"
  ): TypedContractEvent<
    ProviderUpdatedEvent.InputTuple,
    ProviderUpdatedEvent.OutputTuple,
    ProviderUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ReputationUpdated"
  ): TypedContractEvent<
    ReputationUpdatedEvent.InputTuple,
    ReputationUpdatedEvent.OutputTuple,
    ReputationUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "UpdaterAuthorized"
  ): TypedContractEvent<
    UpdaterAuthorizedEvent.InputTuple,
    UpdaterAuthorizedEvent.OutputTuple,
    UpdaterAuthorizedEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "ProviderRegistered(address,string,uint256,string)": TypedContractEvent<
      ProviderRegisteredEvent.InputTuple,
      ProviderRegisteredEvent.OutputTuple,
      ProviderRegisteredEvent.OutputObject
    >;
    ProviderRegistered: TypedContractEvent<
      ProviderRegisteredEvent.InputTuple,
      ProviderRegisteredEvent.OutputTuple,
      ProviderRegisteredEvent.OutputObject
    >;

    "ProviderUpdated(address,uint256,bool)": TypedContractEvent<
      ProviderUpdatedEvent.InputTuple,
      ProviderUpdatedEvent.OutputTuple,
      ProviderUpdatedEvent.OutputObject
    >;
    ProviderUpdated: TypedContractEvent<
      ProviderUpdatedEvent.InputTuple,
      ProviderUpdatedEvent.OutputTuple,
      ProviderUpdatedEvent.OutputObject
    >;

    "ReputationUpdated(address,uint32,uint32)": TypedContractEvent<
      ReputationUpdatedEvent.InputTuple,
      ReputationUpdatedEvent.OutputTuple,
      ReputationUpdatedEvent.OutputObject
    >;
    ReputationUpdated: TypedContractEvent<
      ReputationUpdatedEvent.InputTuple,
      ReputationUpdatedEvent.OutputTuple,
      ReputationUpdatedEvent.OutputObject
    >;

    "UpdaterAuthorized(address,bool)": TypedContractEvent<
      UpdaterAuthorizedEvent.InputTuple,
      UpdaterAuthorizedEvent.OutputTuple,
      UpdaterAuthorizedEvent.OutputObject
    >;
    UpdaterAuthorized: TypedContractEvent<
      UpdaterAuthorizedEvent.InputTuple,
      UpdaterAuthorizedEvent.OutputTuple,
      UpdaterAuthorizedEvent.OutputObject
    >;
  };
}
