import { NextResponse } from 'next/server'

export const runtime = 'nodejs'

/**
 * Mocked provider fulfillment webhook.
 *
 * In production this endpoint belongs to the provider's own systems: when an
 * order ships, an appointment completes, or a lab report is issued, the
 * provider posts a signed artifact here and the agent's verify route consumes
 * it. For the hackathon we simulate that emission deterministically per goal.
 *
 * The artifact is deliberately structured like a real fulfillment record
 * (courier reference, lab report id, appointment id, subscription receipt) so
 * the agent can verify against an actual record rather than a trust-me flag.
 */

const ARTIFACT_TYPES = ['DELIVERY_CONFIRMED', 'APPOINTMENT_COMPLETED', 'LAB_REPORT', 'SUBSCRIPTION_RENEWAL'] as const
type ArtifactType = (typeof ARTIFACT_TYPES)[number]

const REFERENCE_PREFIX: Record<ArtifactType, string> = {
  DELIVERY_CONFIRMED: 'EVRY',
  APPOINTMENT_COMPLETED: 'APT',
  LAB_REPORT: 'LM',
  SUBSCRIPTION_RENEWAL: 'SUB',
}

function hashToId(goalId: number, type: ArtifactType): string {
  let h = 2166136261
  const seed = `${goalId}:${type}`
  for (let i = 0; i < seed.length; i++) {
    h ^= seed.charCodeAt(i)
    h = Math.imul(h, 16777619)
  }
  return (h >>> 0).toString()
}

export async function POST(req: Request) {
  try {
    const { goalId, providerAddress, artifactType } = await req.json()

    if (!goalId || !providerAddress || !artifactType) {
      return NextResponse.json(
        { error: 'goalId, providerAddress and artifactType are required' },
        { status: 400 }
      )
    }
    const type = artifactType as ArtifactType
    if (!(ARTIFACT_TYPES as readonly string[]).includes(type)) {
      return NextResponse.json(
        { error: `Unsupported artifact type. Allowed: ${ARTIFACT_TYPES.join(', ')}` },
        { status: 400 }
      )
    }

    // Deterministic per (goal, type) so re-posting the webhook yields the same record
    const referenceId = hashToId(Number(goalId), type).slice(0, 8)
    const evidenceReference = `${REFERENCE_PREFIX[type]}-${referenceId}`

    const artifact = {
      type,
      providerAddress,
      evidenceReference,
      signedAt: Math.floor(Date.now() / 1000),
      artifactId: `wbhk-${Number(goalId)}-${type.toLowerCase()}-${referenceId}`,
      status: 'FULFILLED',
      summary:
        type === 'DELIVERY_CONFIRMED'
          ? 'Order delivered — courier scan captured at destination'
          : type === 'LAB_REPORT'
            ? 'Lab report issued — report reference generated by laboratory system'
            : type === 'APPOINTMENT_COMPLETED'
              ? 'Appointment completed — clinician confirmed attendance'
              : 'Subscription renewed — billing receipt generated',
    }

    return NextResponse.json({
      success: true,
      goalId,
      webhook: 'PROVIDER_FULFILLMENT',
      artifact,
      note: 'This is the fulfillment record. Submit it to /api/agent/verify — a bare success flag is never accepted as proof.',
    })
  } catch (error: any) {
    return NextResponse.json({ error: error.message || 'Webhook emission failed' }, { status: 500 })
  }
}
