/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IProviderRegistry,
  IProviderRegistryInterface,
} from "../../../contracts/WellnessEscrow.sol/IProviderRegistry";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "providerAddress",
        type: "address",
      },
    ],
    name: "providers",
    outputs: [
      {
        internalType: "address",
        name: "providerAddressOut",
        type: "address",
      },
      {
        internalType: "string",
        name: "serviceName",
        type: "string",
      },
      {
        internalType: "uint256",
        name: "price",
        type: "uint256",
      },
      {
        internalType: "string",
        name: "category",
        type: "string",
      },
      {
        internalType: "uint32",
        name: "completedOrders",
        type: "uint32",
      },
      {
        internalType: "uint32",
        name: "disputes",
        type: "uint32",
      },
      {
        internalType: "bool",
        name: "isActive",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "providerAddress",
        type: "address",
      },
      {
        internalType: "bool",
        name: "success",
        type: "bool",
      },
    ],
    name: "updateReputation",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IProviderRegistry__factory {
  static readonly abi = _abi;
  static createInterface(): IProviderRegistryInterface {
    return new Interface(_abi) as IProviderRegistryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IProviderRegistry {
    return new Contract(address, _abi, runner) as unknown as IProviderRegistry;
  }
}
