/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as wellnessEscrowSol from "./WellnessEscrow.sol";
export { ProviderRegistry__factory } from "./ProviderRegistry__factory";
