/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IProviderRegistry } from "./IProviderRegistry";
export type { WellnessEscrow } from "./WellnessEscrow";
