/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface WellnessEscrowInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "TIMEOUT_DURATION"
      | "agentSigner"
      | "createGoal"
      | "getUserGoalIds"
      | "goals"
      | "nextGoalId"
      | "owner"
      | "paused"
      | "refund"
      | "registry"
      | "renounceOwnership"
      | "setAgentSigner"
      | "setRegistry"
      | "submitVerificationProof"
      | "transferOwnership"
      | "userGoals"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AgentSignerUpdated"
      | "GoalCreated"
      | "GoalRefunded"
      | "GoalVerified"
      | "OwnershipTransferred"
      | "Paused"
      | "RegistryUpdated"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "TIMEOUT_DURATION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "agentSigner",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createGoal",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserGoalIds",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "goals", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "nextGoalId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "refund",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "registry", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setAgentSigner",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setRegistry",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitVerificationProof",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "userGoals",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "TIMEOUT_DURATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "agentSigner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "createGoal", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getUserGoalIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "goals", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "nextGoalId", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "refund", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "registry", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAgentSigner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitVerificationProof",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "userGoals", data: BytesLike): Result;
}

export namespace AgentSignerUpdatedEvent {
  export type InputTuple = [newAgentSigner: AddressLike];
  export type OutputTuple = [newAgentSigner: string];
  export interface OutputObject {
    newAgentSigner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GoalCreatedEvent {
  export type InputTuple = [
    goalId: BigNumberish,
    user: AddressLike,
    provider: AddressLike,
    amount: BigNumberish,
    goalHash: BytesLike,
    timeoutAt: BigNumberish
  ];
  export type OutputTuple = [
    goalId: bigint,
    user: string,
    provider: string,
    amount: bigint,
    goalHash: string,
    timeoutAt: bigint
  ];
  export interface OutputObject {
    goalId: bigint;
    user: string;
    provider: string;
    amount: bigint;
    goalHash: string;
    timeoutAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GoalRefundedEvent {
  export type InputTuple = [
    goalId: BigNumberish,
    user: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [goalId: bigint, user: string, amount: bigint];
  export interface OutputObject {
    goalId: bigint;
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GoalVerifiedEvent {
  export type InputTuple = [
    goalId: BigNumberish,
    provider: AddressLike,
    amount: BigNumberish,
    verificationHash: BytesLike
  ];
  export type OutputTuple = [
    goalId: bigint,
    provider: string,
    amount: bigint,
    verificationHash: string
  ];
  export interface OutputObject {
    goalId: bigint;
    provider: string;
    amount: bigint;
    verificationHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RegistryUpdatedEvent {
  export type InputTuple = [newRegistry: AddressLike];
  export type OutputTuple = [newRegistry: string];
  export interface OutputObject {
    newRegistry: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface WellnessEscrow extends BaseContract {
  connect(runner?: ContractRunner | null): WellnessEscrow;
  waitForDeployment(): Promise<this>;

  interface: WellnessEscrowInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  TIMEOUT_DURATION: TypedContractMethod<[], [bigint], "view">;

  agentSigner: TypedContractMethod<[], [string], "view">;

  createGoal: TypedContractMethod<
    [provider: AddressLike, goalHash: BytesLike],
    [bigint],
    "payable"
  >;

  getUserGoalIds: TypedContractMethod<[user: AddressLike], [bigint[]], "view">;

  goals: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint
      ] & {
        goalId: bigint;
        user: string;
        provider: string;
        amount: bigint;
        goalHash: string;
        verificationHash: string;
        createdAt: bigint;
        timeoutAt: bigint;
        status: bigint;
      }
    ],
    "view"
  >;

  nextGoalId: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  paused: TypedContractMethod<[], [boolean], "view">;

  refund: TypedContractMethod<[goalId: BigNumberish], [void], "nonpayable">;

  registry: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setAgentSigner: TypedContractMethod<
    [_agentSigner: AddressLike],
    [void],
    "nonpayable"
  >;

  setRegistry: TypedContractMethod<
    [_registryAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  submitVerificationProof: TypedContractMethod<
    [goalId: BigNumberish, verificationHash: BytesLike, signature: BytesLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  userGoals: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "TIMEOUT_DURATION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "agentSigner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "createGoal"
  ): TypedContractMethod<
    [provider: AddressLike, goalHash: BytesLike],
    [bigint],
    "payable"
  >;
  getFunction(
    nameOrSignature: "getUserGoalIds"
  ): TypedContractMethod<[user: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "goals"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint
      ] & {
        goalId: bigint;
        user: string;
        provider: string;
        amount: bigint;
        goalHash: string;
        verificationHash: string;
        createdAt: bigint;
        timeoutAt: bigint;
        status: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "nextGoalId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "refund"
  ): TypedContractMethod<[goalId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "registry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setAgentSigner"
  ): TypedContractMethod<[_agentSigner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setRegistry"
  ): TypedContractMethod<[_registryAddress: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "submitVerificationProof"
  ): TypedContractMethod<
    [goalId: BigNumberish, verificationHash: BytesLike, signature: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "userGoals"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  getEvent(
    key: "AgentSignerUpdated"
  ): TypedContractEvent<
    AgentSignerUpdatedEvent.InputTuple,
    AgentSignerUpdatedEvent.OutputTuple,
    AgentSignerUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "GoalCreated"
  ): TypedContractEvent<
    GoalCreatedEvent.InputTuple,
    GoalCreatedEvent.OutputTuple,
    GoalCreatedEvent.OutputObject
  >;
  getEvent(
    key: "GoalRefunded"
  ): TypedContractEvent<
    GoalRefundedEvent.InputTuple,
    GoalRefundedEvent.OutputTuple,
    GoalRefundedEvent.OutputObject
  >;
  getEvent(
    key: "GoalVerified"
  ): TypedContractEvent<
    GoalVerifiedEvent.InputTuple,
    GoalVerifiedEvent.OutputTuple,
    GoalVerifiedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "RegistryUpdated"
  ): TypedContractEvent<
    RegistryUpdatedEvent.InputTuple,
    RegistryUpdatedEvent.OutputTuple,
    RegistryUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "AgentSignerUpdated(address)": TypedContractEvent<
      AgentSignerUpdatedEvent.InputTuple,
      AgentSignerUpdatedEvent.OutputTuple,
      AgentSignerUpdatedEvent.OutputObject
    >;
    AgentSignerUpdated: TypedContractEvent<
      AgentSignerUpdatedEvent.InputTuple,
      AgentSignerUpdatedEvent.OutputTuple,
      AgentSignerUpdatedEvent.OutputObject
    >;

    "GoalCreated(uint256,address,address,uint256,bytes32,uint256)": TypedContractEvent<
      GoalCreatedEvent.InputTuple,
      GoalCreatedEvent.OutputTuple,
      GoalCreatedEvent.OutputObject
    >;
    GoalCreated: TypedContractEvent<
      GoalCreatedEvent.InputTuple,
      GoalCreatedEvent.OutputTuple,
      GoalCreatedEvent.OutputObject
    >;

    "GoalRefunded(uint256,address,uint256)": TypedContractEvent<
      GoalRefundedEvent.InputTuple,
      GoalRefundedEvent.OutputTuple,
      GoalRefundedEvent.OutputObject
    >;
    GoalRefunded: TypedContractEvent<
      GoalRefundedEvent.InputTuple,
      GoalRefundedEvent.OutputTuple,
      GoalRefundedEvent.OutputObject
    >;

    "GoalVerified(uint256,address,uint256,bytes32)": TypedContractEvent<
      GoalVerifiedEvent.InputTuple,
      GoalVerifiedEvent.OutputTuple,
      GoalVerifiedEvent.OutputObject
    >;
    GoalVerified: TypedContractEvent<
      GoalVerifiedEvent.InputTuple,
      GoalVerifiedEvent.OutputTuple,
      GoalVerifiedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "RegistryUpdated(address)": TypedContractEvent<
      RegistryUpdatedEvent.InputTuple,
      RegistryUpdatedEvent.OutputTuple,
      RegistryUpdatedEvent.OutputObject
    >;
    RegistryUpdated: TypedContractEvent<
      RegistryUpdatedEvent.InputTuple,
      RegistryUpdatedEvent.OutputTuple,
      RegistryUpdatedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
